name: Build
permissions:
  contents: write
on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Create a release build'
        required: false
        type: boolean

  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/**'
      - 'src/**'
      - 'action.yml'
      - 'package-lock.json'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: 'node_modules'
          key: node-${{ hashFiles('package-lock.json') }}
          restore-keys: node-

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Create release build
        if: ${{ inputs.release }}
        run: |
          npm install
          npm run build
      - name: Create debug build
        if: ${{ !inputs.release }}
        run: |
          git config --global user.email "yuyu.energy01@gmail.com"
          git config --global user.name "y-a-m-a-y-u"
          git fetch origin build
          git switch build
          git merge master
          npm install
          npm run build
      - name: Push to GitHub
        uses: EndBug/add-and-commit@v9.1.1
        with:
          add: '-f ./dist'
          author_name: 'y-a-m-a-y-u'
          author_email: 'yuyu.energy01@gmail.com'
          message: 'build: Build action'
